#!/bin/bash

#FG Colours
color_fg_none="\e[0m"
color_fg_lightGreen="\e[38;5;47m"
color_fg_lightBlue="\e[38;5;75m"
color_fg_lightYellow="\e[38;5;229m"
color_fg_lightPink="\e[38;5;211m"
color_fg_lightPurple="\e[38;5;163m"
color_fg_red="\e[38;5;196m"

#BG Colours
color_bg_purple="\e[48;5;54m"


amanha=$(date -d "+1 days" | awk '{print $1}' ) 
dia="$@"

if [[ $dia == "" ]]; then dia="hoj"; fi

echo -e "\
  amanha $amanha
  segunda Mon
  terça Tue
  quarta Wed
  quinta Thu
  sexta Fri
  sabado Sat
  domingo Sun" > /tmp/.queryclassicode;

if [[ "${dia}" != "hoj" ]] && [[ "${dia}" != "ama" ]] && [[ "${dia}" != "ont" ]] && [[ "${dia}" != "seg" ]] && [[ "${dia}" != "ter" ]] && [[ "${dia}" != "qua" ]] && [[ "${dia}" != "qui" ]] && [[ "${dia}" != "sex" ]] && [[ "${dia}" != "sab" ]] && [[ "${dia}" != "dom" ]]; then
  echo -e "\
  $color_fg_lightYellow Por favor especifique um dia
    
    $color_fg_lightBlue Opções:
     $color_fg_lightGreen hoj $color_fg_lightPink #Exibe o classico hoje ($(date | awk '{print $1}'))
     $color_fg_lightGreen ama $color_fg_lightPink #Exibe o classico de amanhã ($(date -d "+1 days" | awk '{print $1}'))
     $color_fg_lightGreen ont $color_fg_lightPink #Exibe o classico de ontem ($(date -d "-1 days" | awk '{print $1}'))
     $color_fg_lightGreen seg $color_fg_lightPink #Exibe o classico de Segunda
     $color_fg_lightGreen ter $color_fg_lightPink #Exibe o classico de Terça
     $color_fg_lightGreen qua $color_fg_lightPink #Exibe o classico de Quarta
     $color_fg_lightGreen qui $color_fg_lightPink #Exibe o classico de Quinta
     $color_fg_lightGreen sex $color_fg_lightPink #Exibe o classico de Sexta
     $color_fg_lightGreen sab $color_fg_lightPink #Exibe o classico de Sábado
     $color_fg_lightGreen dom $color_fg_lightPink #Exibe o classico de Domingo
      
  $color_fg_lightBlue Ex:$color_fg_lightYellow$ classicode$color_fg_lightGreen qua $color_fg_none 
  "
else

  if [ "$dia" == "ama" ]; then
    diaen=$(date -d "+1 days" | awk '{print $1}' ) 
  elif [ "$dia" == "ont" ]; 
  then
    diaen=$(date -d "-1 days" | awk '{print $1}' ) 
  elif [ "$dia" == "hoj" ];
  then
    diaen=$(date | awk '{print $1}' ) 
  else
    diaen=$(cat /tmp/.queryclassicode | ag -i --nocolor $dia | awk '{ print $2 }')
  fi
  
  if [[ $diaen == "Mon" ]]; then
    varquery='segunda\-feira\s.*:';
  elif [[ $diaen == "Tue" ]]; then
    varquery='terça\-feira\s.*:';
  elif [[ $diaen == "Wed" ]]; then
    varquery='quarta\-feira\s.*:';
  elif [[ $diaen == "Thu" ]]; then
    varquery='quinta\-feira\s.*:';
  elif [[ $diaen == "Fri" ]]; then
    varquery='sexta\-feira\s.*:';
  elif [[ $diaen == "Sat" ]]; then
    varquery='sábado\s.*:';
  elif [[ $diaen == "Sun" ]]; then
    varquery='domingo\s.*:';
  else
    echo "Falha ao obter dia da semana";
  fi 

  curl -s https://www.testapramim.com.br/mcdonalds-do-dia/ | ag -i $varquery | cut -f1 -d: | cut -c 13-100 > /tmp/.classicododia

  echo -e "$color_fg_lightPink  (McDonalds)$color_fg_lightYellow $( cat /tmp/.classicododia ) $color_fg_none"


fi
