#!/bin/bash

#FG Colours
color_fg_none="\e[0m"
color_fg_lightGreen="\e[38;5;47m"
color_fg_lightBlue="\e[38;5;75m"
color_fg_lightYellow="\e[38;5;229m"
color_fg_lightPink="\e[38;5;211m"
color_fg_lightPurple="\e[38;5;163m"
color_fg_orange="\e[38;5;208m"
color_fg_red="\e[38;5;196m"

#BG Colours
color_bg_purple="\e[48;5;54m"

dia="$(date +%A)"
horaatual="$(date +%H:%M)"

tarefasdodia | awk "\$2 > \"$horaatual\" && \$2 !~ \"$dia\" " | awk 'FNR==1' > /tmp/.proxtarefa;
cat /tmp/.proxtarefa | awk '{ print $2 }' > /tmp/.proxtarefahour

tarefasde ama | awk 'FNR==2' > /tmp/.primeiratarefa;
cat /tmp/.primeiratarefa | awk '{ print $2 }' > /tmp/.primeiratarefahour

old=$horaatual
new=$(cat /tmp/.proxtarefahour)     

if [ "$new" == "" ]; then
  new=$(cat /tmp/.primeiratarefahour)
else
  new=$(cat /tmp/.proxtarefahour)     
fi

if [[ $old > $new ]]; then
 old=00:00;
 catproxtarefa="cat /tmp/.primeiratarefa"
 time_now_in_sec=$(date +%s)
 midnight=$(date -d "tomorrow 00:00" +%s)
 minutes_left_to_midnight=$(((midnight - time_now_in_sec) / 60))
else
 minutes_left_to_midnight="0"
 catproxtarefa="cat /tmp/.proxtarefa"
fi

IFS=: read old_hour old_min <<< "$old"
IFS=: read hour min <<< "$new"

# convert the date "1970-01-01 hour:min:00" in seconds from Unix EPOCH time
sec_old=$(date -d "1970-01-01 $old_hour:$old_min:00" +%s)
	sec_new=$(date -d "1970-01-01 $hour:$min:00" +%s)
	sec_mid=$(( ($minutes_left_to_midnight * 60 ) ))
	total_minutes=$(( (sec_new - (sec_old - sec_mid)) / 60))
final_hour=$(( total_minutes / 60 ))
final_minute=$(( total_minutes - final_hour * 60 ))
hsym="h"
msym="m"
if [[ $final_hour = 0 ]]; then
final_hour=""
hour_complement=""
elif [[ $final_hour = 1 ]]; then
hour_complement=" hora$color_fg_lightYellow e " 
else
hour_complement=" horas$color_fg_lightYellow e "
fi 

echo -e "\
$color_fg_lightYellow Faltam\
$color_fg_lightBlue $final_hour$hour_complement$color_fg_lightBlue$final_minute min\
$color_fg_lightYellow para a próxima tarefa"
$catproxtarefa

