#!/bin/bash

if [[ "$1" == "" ]]; then
  echo -e "NOW:$tarefanow NEXT:[$timerm m]$tarefanext;"
else
  if [[ "$1" == "now" ]]; then
    tarefanow | awk 'FNR==2 {$1=$1;print}' | ag -o "\s\w\D.*" | cut -f1 -d[ | cut -c 2-244
  elif [[ "$1" == "left" ]]; then
    tarefanow | awk 'FNR==3 { print $4 }';
  elif [[ "$1" == "next" ]]; then
    tarefanow | awk 'FNR==4 {$1=$1;print}' | ag -o "\s\w\D.*" | cut -f1 -d[ | cut -c 2-244
  else
    echo -e "parametro invalido"
  fi  
fi
